version: '3'
services:
  web:
    build: .
    volumes:
     - ./web/cairo:/cairo
    ports:
     - "9000:9000"
    links: 
     - app-db
    stdin_open: true
    command: play -Dconfig.file=conf/dev-docker.conf run

  app-db:
    restart: always
    image: "postgres:9.1"
    environment:
      POSTGRES_PASSWORD: 14FeDyAr
    ports:
     - '5432:5432'
